<?xml version="1.0"?>
<robot name="vtrex" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:arg name="laser_enabled" default="true" />
  <xacro:property name="PI" value="3.1415926535897931" />

  <xacro:property name="wheelbase" value="0.70382" />
  <xacro:property name="track" value="0.6296" />
  <xacro:property name="wheel_vertical_offset" value="0.1651" />
  <xacro:property name="footprint_vertical_offset" value=".24866" />

  <xacro:property name="wheel_radius" value="0.1648" />
  <xacro:property name="wheel_width" value="0.127" />

  <xacro:property name="chassis_length" value="0.97214" />
  <xacro:property name="chassis_width" value="0.48381" />
  <xacro:property name="chassis_height" value="0.28" />

  <xacro:property name="dummy_inertia" value="1e-09"/>

  <xacro:property name="cameraSize" value="0.025"/>
  <xacro:property name="cameraMass" value="0.05"/>

  <xacro:include filename="$(find vtrex_description)/urdf/vtrex.gazebo" />
  <xacro:include filename="$(find vtrex_description)/urdf/materials.xacro" />



<xacro:macro name="wheel" params="prefix *joint_pose">

    <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
       <mesh filename="package://vtrex_description/meshes/wheel.STL"/>
</geometry>
        <material name="black" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
         <cylinder radius="${wheel_radius}" length="${wheel_width/4}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="2.637"/>
        <inertia
          ixx="0.02467" ixy="0" ixz="0"
          iyy="0.04411" iyz="0"
          izz="0.02467"/>
      </inertial>
    </link>

    <gazebo reference="${prefix}_wheel_link">
      <material>Gazebo/DarkGrey</material>
	<mu1 value="20.00"/>
	<mu2 value="20.00"/>
	<!--kp value="10000000.0"/>
	<kd value="1.0" /-->
	<fdir1 value="1 0 0"/>
    </gazebo>

    <joint name="${prefix}_wheel" type="continuous">
      <parent link="chassis_link"/>
      <child link="${prefix}_wheel_link"/>
      <xacro:insert_block name="joint_pose"/>
      <axis xyz="0 1 0" />
    </joint>

    <transmission name="${prefix}_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_wheel">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_actuator">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  <xacro:wheel prefix="front_left">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="front_right">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="rear_left">
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="rear_right">
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>

  <link name="base_link"></link>

  <joint name="base_link_joint" type="fixed">

    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="chassis_link" />
  </joint>


  <xacro:property name="chassis_cg_offset_y" value="0.013" />
  <xacro:property name="chassis_cg_offset_x" value="0.029" />

  <link name="chassis_link">
    <visual>
      <origin xyz="-${chassis_cg_offset_x} ${chassis_cg_offset_y} ${footprint_vertical_offset}" rpy="0 0 0"/>
      <geometry>
       <mesh filename="package://vtrex_description/meshes/TREX.STL"/>
      </geometry>
<material name="black" />
     </visual>
    <collision>
      <origin xyz="-${chassis_cg_offset_x} ${chassis_cg_offset_y} ${footprint_vertical_offset}" rpy="0 0 0"/>
      <geometry>
       <mesh filename="package://vtrex_description/meshes/TREX.STL"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0  ${chassis_cg_offset_y} ${footprint_vertical_offset}" rpy="${PI/2} 0 0"/>
      <mass value="50.18"/>
      <inertia
        ixx="1.82808624" ixy="0.05708591" ixz="-0.01280581"
        iyy="5.010635369" iyz="0.00370272"
        izz="3.90064832"/>
      </inertial>
  </link>
    <gazebo reference="chassis_link">
      <material>Gazebo/DarkGrey</material>
    </gazebo>
<!--############################################wheelscover#################################################-->

  <xacro:property name="wheel_cover_y_spacing" value="0.2350" />
  <xacro:property name="wheel_cover_z_spacing" value="0.3427" />

    <link name="left_wheel_cover_link">
      <visual>
        <origin xyz="0 -${wheel_cover_y_spacing} ${wheel_cover_z_spacing}" rpy="${PI/2} 0 0"/>
        <geometry>
       <mesh filename="package://vtrex_description/meshes/wheelscover.STL"/>
        </geometry>
        <material name="red" />
      </visual>
      <collision>
        <origin xyz="0 -${wheel_cover_y_spacing} ${wheel_cover_z_spacing}" rpy="${PI/2} 0 0"/>
        <geometry>
         <mesh filename="package://vtrex_description/meshes/wheelscover.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.3"/>
        <inertia
          ixx="0.00" ixy="0" ixz="0"
          iyy="0.01" iyz="0"
          izz="0.01"/>
      </inertial>
    </link>

    <link name="right_wheel_cover_link">
      <visual>
        <origin xyz="0 -${wheel_cover_y_spacing} ${wheel_cover_z_spacing}" rpy="${PI/2} 0 0"/>
        <geometry>
       <mesh filename="package://vtrex_description/meshes/wheelscover.STL"/>
        </geometry>
        <material name="red" />
      </visual>
      <collision>
        <origin xyz="0 -${wheel_cover_y_spacing} ${wheel_cover_z_spacing}" rpy="${PI/2} 0 0"/>
        <geometry>
         <mesh filename="package://vtrex_description/meshes/wheelscover.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.3"/>
        <inertia
          ixx="0.00" ixy="0" ixz="0"
          iyy="0.01" iyz="0"
          izz="0.01"/>
      </inertial>
    </link>

    <gazebo reference="left_wheel_cover_link">
      <material>Gazebo/Red</material>
    </gazebo>
    <gazebo reference="right_wheel_cover_link">
      <material>Gazebo/Red</material>
    </gazebo>

     <joint name="left_wheel_cover" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="chassis_link"/>
      <child link="left_wheel_cover_link" />
    </joint>
    <joint name="right_wheel_cover" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 ${PI}" />
      <parent link="chassis_link"/>
      <child link="right_wheel_cover_link" />
    </joint>
  

<!-- ###################################### imu ########################################## -->

  <link name="imu_link">
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="${dummy_inertia}" ixy="0.0" ixz="0.0" iyy="${dummy_inertia}" iyz="0.0" izz="${dummy_inertia}"/>
    </inertial>
  </link>
  <joint name="imu_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="chassis_link" />
    <child link="imu_link" />
  </joint>

<!-- ###################################### laser ########################################## -->

  <link name="laser_mount_link">
	<visual>
         <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <mesh filename="package://vtrex_description/meshes/accessories/laser_mount.STL"/>
          </geometry>
        </visual>
        <collision>
         <origin xyz="0 -${wheel_cover_y_spacing} ${wheel_cover_z_spacing}" rpy="${PI/2} 0 0"/>
         <geometry>
          <mesh filename="package://vtrex_description/meshes/accessories/laser_mount.STL"/>
         </geometry>
        </collision>
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="${dummy_inertia}" ixy="0.0" ixz="0.0" iyy="${dummy_inertia}" iyz="0.0" izz="${dummy_inertia}"/>
    </inertial>
  </link>

<gazebo reference="laser_mount_link">
      <material>Gazebo/DarkGrey</material>
    </gazebo>

  <joint name="laser_mount_joint" type="fixed">
    <origin xyz="${0.496+chassis_cg_offset_x} 0 ${footprint_vertical_offset+0.031}" rpy="0 0 0" />
    <parent link="chassis_link" />
    <child link="laser_mount_link" />
  </joint>

</robot>
